spring:
  application:
    name: raizes-nordeste

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass

  jpa:
    hibernate:
      ddl-auto: none

app:
  jwt:
    issuer: raizes-nordeste
    secret: ${JWT_SECRET:segredo-forte-de-pelo-menos-32-bytes}
  gateway:
    webhook-secret: ${WEBHOOK_SECRET:segredo-forte-para-autenticacao-no-webhook}

springdoc:
  override-with-generic-response: false
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    org.springframework.security: debug